apiVersion: apps/v1
kind: Deployment

metadata:
  name: faceattendance-deployment
  labels:
    app: faceattendance

spec:
  replicas: 2

  selector:
    matchLabels:
      app: faceattendance

  template:
    metadata:
      labels:
        app: faceattendance

    spec:
      containers:
      - name: faceattendance-container

        image: faceattendance:latest

        imagePullPolicy: Never
 
        ports:
        - containerPort: 5000

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        env:
        - name: FLASK_ENV
          value: "production"